settings:
  debug: false
  updater: true
  prefix: '&7[&8BarbedWire&7]'

msg:
  noperm: '&cYou dont have enough permissions to do that.'
  reloaded: '&7was reloaded.'
  
item:
  material: 'SHEARS'
  mustusetobreak: true
  protect-barbedwire: true
  protect-info: 'protect the BarbedWire if the player doesnt have the permission to break it. (bw.use)'

oncontact:
  damage: 2.5
  particle-toggle: true
  particle-type: 'MOBSPAWNER_FLAMES'
  particle-info: 'https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Effect.html'
  sound-toggle: true
  sound-type: 'CLICK'
  sound-volume: 1.0
  sound-pitch: 1.0
  sound-info: 'https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html'

onbreak:
  dropblock: false
  remove-durability: 2
  particle-toggle: true
  particle-type: 'MOBSPAWNER_FLAMES'
  particle-info: 'https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Effect.html'
  sound-toggle: true
  sound-type: 'CLICK'
  sound-volume: 1.0
  sound-pitch: 1.0
  sound-info: 'https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html'
